version: '3.4'

services:
  tempmon:
    image: tempmon
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:5000
    volumes:
      - type: bind
        source: ~/data
        target: /app/data
    restart: unless-stopped
